# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bde545ba491664071913b498098f5c4652c6193792d1ec6ae8ac19bda2b4304170b4947685d075860e7bb75c7dac2355ad634f491edfbf61bbcdca1a9a2467eb

test:
  secret_key_base: e5aefc0c85983453979c2821e8dac43b2496e7c3c671b4ce00f3179448d5556255f505c8647f746702877da70a9e33f58bf06f095329a7fdcdb239fd4d5630ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
